import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import { cx } from "cva";

const montserrat = Montserrat({
    weight: ["400", "500", "600", "700", "900"],
    subsets: ["latin"],
    variable: "--font-montserrat",
});

export const metadata: Metadata = {
    title: "Concentrix Tour",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cx(["antialiased", montserrat.variable])}>
            <body
                className={cx([
                    "flex flex-col relative",
                    "w-full min-h-lvh",
                    montserrat.variable,
                ])}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
