import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer, Header, LoaderOverlay } from "@/components";
import { cx } from "cva";
import { Suspense } from "react";
import { cookies } from "next/headers";

const montserrat = Montserrat({
    weight: ["400", "500", "600", "700", "900"],
    subsets: ["latin"],
    variable: "--font-montserrat",
});

export const metadata: Metadata = {
    title: "Concentrix Tour",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const theme = cookieStore.get("theme")?.value || "light";
    return (
        <html
            lang="en"
            className={cx([
                "antialiased scroll-smooth",
                montserrat.variable,
                theme === "dark" ? "dark" : "",
            ])}
        >
            <body
                className={cx([
                    "flex flex-col relative",
                    "w-full min-h-lvh",
                    montserrat.variable,
                ])}
            >
                <Suspense fallback={<LoaderOverlay />} />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
